"""empty message

Revision ID: a885be2d162b
Revises: 5f4600e20b72
Create Date: 2022-03-03 17:24:12.916965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a885be2d162b'
down_revision = '5f4600e20b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
