"""empty message

Revision ID: cbf896f5a02e
Revises: a885be2d162b
Create Date: 2022-03-03 17:25:11.890142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf896f5a02e'
down_revision = 'a885be2d162b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
